### ISSUE TITLE
Gstat error

### ISSUE THREAD

**Issue by tdegeus** [tdegeus/GooseSLURM#8]
I am getting the following output

```bash
Traceback (most recent call last):
  File "/home/tdegeus/opt/bin/Gstat", line 192, in <module>
    gs.table.print_columns(lines, columns, header, args['no_truncate'], args['sep'], args['width'])
  File "/home/tdegeus/.local/lib/python3.6/site-packages/GooseSLURM/table.py", line 193, in print_columns
    hline[key].data = '=' * hline[key].width
TypeError: can't multiply sequence by non-int of type 'NoneType'
```

**Comment by tdegeus** [comment]
This is not reproducible
